-- 20260517000000_summer_meadows_parcels.sql
-- GENERATED by scripts/gen-parcel-migration.mjs from a one-time pull of the
-- 45 Summer Meadows parcels (Summerwind/Summerlane Ave NE, Grand
-- Rapids, Kent County MI) off Kent County's free ParcelsWithCondos
-- FeatureServer. Lot polygons live in our DB; the map renders from here —
-- no external GIS dependency at runtime.

alter table public.lots add column if not exists geometry_geojson jsonb;
alter table public.lots add column if not exists parcel_pin text;

create unique index if not exists lots_parcel_pin_key
  on public.lots (parcel_pin) where parcel_pin is not null;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127009', '4331', 'Summerwind Ave NE', '411035127009', $geo${"type":"Polygon","coordinates":[[[-85.58212626760118,43.04134758321141],[-85.58261638056162,43.04135386226977],[-85.58262085051977,43.041134391299565],[-85.58213055188868,43.041128086554274],[-85.58212626760118,43.04134758321141]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127021', '4250', 'Summerwind Ave NE', '411035127021', $geo${"type":"Polygon","coordinates":[[[-85.58114090662917,43.0397118981749],[-85.58123335699611,43.03992908114284],[-85.58187265296621,43.0399200364419],[-85.58186358843402,43.03983961849238],[-85.58186077396873,43.03982397932296],[-85.58185505031287,43.039808782239255],[-85.58184660883248,43.039794272799625],[-85.581835530943,43.039780751478126],[-85.58181759842903,43.03976110089254],[-85.58179601196775,43.039742093020514],[-85.58178011340928,43.039726948819315],[-85.5817666962055,43.03971051598909],[-85.58176225197103,43.039703291051154],[-85.58114090662917,43.0397118981749]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128015', '4365', 'Summerlane Ave NE', '411035128015', $geo${"type":"Polygon","coordinates":[[[-85.58088637341618,43.04190632858202],[-85.58137680911071,43.04191359773071],[-85.58138046038809,43.04169410840018],[-85.58089122350647,43.04168682660283],[-85.58088877602862,43.04180400075553],[-85.58088637341618,43.04190632858202]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128004', '4350', 'Summerwind Ave NE', '411035128004', $geo${"type":"Polygon","coordinates":[[[-85.58138046038809,43.04169410840018],[-85.58187284135926,43.04170143708185],[-85.58187682704897,43.04148191647525],[-85.58138411109499,43.0414745913741],[-85.58138046038809,43.04169410840018]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128017', '4389', 'Summerlane Ave NE', '411035128017', $geo${"type":"Polygon","coordinates":[[[-85.58087510599469,43.042390447492345],[-85.58136874556347,43.0423960414881],[-85.58136878313046,43.04239377427947],[-85.58137312134791,43.04213311512664],[-85.58088126113954,43.0421258061761],[-85.58087559307454,43.04236949809291],[-85.58087510599469,43.042390447492345]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128005', '4338', 'Summerwind Ave NE', '411035128005', $geo${"type":"Polygon","coordinates":[[[-85.58138411109499,43.0414745913741],[-85.58187682704897,43.04148191647525],[-85.58187852412986,43.041389447607656],[-85.58188100066208,43.04126244897716],[-85.58138776231513,43.041255101750394],[-85.58138411109499,43.0414745913741]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127032', '4378', 'Summerlane Ave NE', '411035127032', $geo${"type":"Polygon","coordinates":[[[-85.58014524442972,43.04212388702081],[-85.5801467730089,43.04212388687691],[-85.5806406581075,43.04212382331641],[-85.58064528484495,43.041904323730044],[-85.58015080277951,43.041904393640486],[-85.58014927827622,43.04190439374143],[-85.58014524442972,43.04212388702081]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128001', '4386', 'Summerwind Ave NE', '411035128001', $geo${"type":"Polygon","coordinates":[[[-85.58136874556347,43.0423960414881],[-85.58185745192971,43.04240157781623],[-85.58185775391509,43.042388429828414],[-85.58186344731287,43.042140410524134],[-85.58137312134791,43.04213311512664],[-85.58136878313046,43.04239377427947],[-85.58136874556347,43.0423960414881]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127008', '4343', 'Summerwind Ave NE', '411035127008', $geo${"type":"Polygon","coordinates":[[[-85.58211966226052,43.041567021365616],[-85.58261194847987,43.04157335997495],[-85.58261638056162,43.04135386226977],[-85.58212626760118,43.04134758321141],[-85.58212540168958,43.04139292563277],[-85.58211966226052,43.041567021365616]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128008', '4300', 'Summerwind Ave NE', '411035128008', $geo${"type":"Polygon","coordinates":[[[-85.58139510151693,43.04081609493308],[-85.5818877371019,43.04082342078351],[-85.58188951528533,43.04060389635784],[-85.58139875265908,43.04059660527684],[-85.58139510151693,43.04081609493308]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127031', '4366', 'Summerlane Ave NE', '411035127031', $geo${"type":"Polygon","coordinates":[[[-85.58014927827622,43.04190439374143],[-85.58015080277951,43.041904393640486],[-85.58064528484495,43.041904323730044],[-85.58064736893115,43.0418048256016],[-85.58064987252142,43.041684796855165],[-85.58015486935118,43.04168487231343],[-85.58015331266004,43.041684872754736],[-85.58014927827622,43.04190439374143]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128007', '4314', 'Summerwind Ave NE', '411035128007', $geo${"type":"Polygon","coordinates":[[[-85.58139145088802,43.041035611991724],[-85.58188528582076,43.04104295259643],[-85.58188642712825,43.04098498369552],[-85.5818877371019,43.04082342078351],[-85.58139510151693,43.04081609493308],[-85.58139145088802,43.041035611991724]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127022', '4262', 'Summerwind Ave NE', '411035127022', $geo${"type":"Polygon","coordinates":[[[-85.58123335699611,43.03992908114284],[-85.58135746059955,43.040220570413155],[-85.58136333470065,43.04021869696729],[-85.58141295022064,43.04020576818392],[-85.58146967791807,43.04019495951566],[-85.58153075214184,43.04018640990195],[-85.58158871715459,43.04017761870699],[-85.58163144931642,43.04017612362857],[-85.58175235005183,43.04017352654332],[-85.5818804927922,43.04017351446085],[-85.58188047855927,43.04017277240016],[-85.5818790050345,43.03997666366048],[-85.58187265296621,43.0399200364419],[-85.58123335699611,43.03992908114284]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127007', '4355', 'Summerwind Ave NE', '411035127007', $geo${"type":"Polygon","coordinates":[[[-85.58211350718314,43.04178650984939],[-85.58260747825808,43.04179285834441],[-85.58261194847987,43.04157335997495],[-85.58211966226052,43.041567021365616],[-85.58211434191539,43.04172818775425],[-85.58211350718314,43.04178650984939]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127016', '4247', 'Summerwind Ave NE', '411035127016', $geo${"type":"Polygon","coordinates":[[[-85.58218654078415,43.03960673152079],[-85.58218811697988,43.03961266962283],[-85.58219002623721,43.039631748996904],[-85.58218890663632,43.03965088759615],[-85.58218478924661,43.03966978375466],[-85.58217766919837,43.03968819021024],[-85.58216772939984,43.03970588540234],[-85.58215503920358,43.03972259467786],[-85.58214003825984,43.03973784644359],[-85.5821285151189,43.039751140422645],[-85.58211910541905,43.03976534507712],[-85.58211199042286,43.03978021144601],[-85.58210728066177,43.03979560126458],[-85.5821049694313,43.0398112678337],[-85.5821050338303,43.03981831924667],[-85.58264782540624,43.039804502141386],[-85.58265300389915,43.03955450848144],[-85.58218654078415,43.03960673152079]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127018', '4223', 'Summerwind Ave NE', '411035127018', $geo${"type":"Polygon","coordinates":[[[-85.58191196303224,43.03947470869735],[-85.58192336882038,43.03947258444606],[-85.58194924562872,43.03947008788586],[-85.58197531602629,43.039469811832355],[-85.58200128012709,43.03947173204199],[-85.58202676364989,43.03947588044018],[-85.58205142881688,43.03948215038545],[-85.58207490008706,43.03949049101742],[-85.58208921016421,43.039497172491785],[-85.58261891940452,43.03891750417405],[-85.58177419344992,43.03890859054765],[-85.58191196303224,43.03947470869735]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128013', '4341', 'Summerlane Ave NE', '411035128013', $geo${"type":"Polygon","coordinates":[[[-85.58089581211067,43.04146735452606],[-85.58138411109499,43.0414745913741],[-85.58138776231513,43.041255101750394],[-85.5809003997785,43.04124785530053],[-85.58089581211067,43.04146735452606]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128014', '4353', 'Summerlane Ave NE', '411035128014', $geo${"type":"Polygon","coordinates":[[[-85.58089122350647,43.04168682660283],[-85.58138046038809,43.04169410840018],[-85.58138411109499,43.0414745913741],[-85.58089581211067,43.04146735452606],[-85.58089122350647,43.04168682660283]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127033', '4390', 'Summerlane Ave NE', '411035127033', $geo${"type":"Polygon","coordinates":[[[-85.58014050008934,43.042382035971436],[-85.58014204198369,43.04238205387568],[-85.58063508923328,43.04238772651333],[-85.58063535085466,43.0423753361003],[-85.5806406581075,43.04212382331641],[-85.5801467730089,43.04212388687691],[-85.58014524442972,43.04212388702081],[-85.58014050008934,43.042382035971436]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128003', '4362', 'Summerwind Ave NE', '411035128003', $geo${"type":"Polygon","coordinates":[[[-85.58137680911071,43.04191359773071],[-85.58186851819728,43.041920906412415],[-85.58187014967102,43.04184981523188],[-85.58187284135926,43.04170143708185],[-85.58138046038809,43.04169410840018],[-85.58137680911071,43.04191359773071]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127020', '4238', 'Summerwind Ave NE', '411035127020', $geo${"type":"Polygon","coordinates":[[[-85.58099860589047,43.039377655277676],[-85.58114090662917,43.0397118981749],[-85.58176225197103,43.039703291051154],[-85.58175598999532,43.03969306683172],[-85.58174807383183,43.03967481959107],[-85.58174313980543,43.03965601927588],[-85.58174118717353,43.03963666589431],[-85.58174234503086,43.039617527167294],[-85.58174649992489,43.03959863062882],[-85.58175362009132,43.03958022419956],[-85.58176359736075,43.03956252864719],[-85.5817699428533,43.039554201581865],[-85.58112516971558,43.03921226973963],[-85.58099860589047,43.039377655277676]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127028', '4330', 'Summerlane Ave NE', '411035127028', $geo${"type":"Polygon","coordinates":[[[-85.58016138040566,43.0412458584491],[-85.58016292783486,43.04124585810545],[-85.58065904979549,43.04124577047016],[-85.58066360128507,43.04102627163466],[-85.58016695694671,43.04102633714087],[-85.58016541433346,43.041026337433664],[-85.58016138040566,43.0412458584491]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128016', '4377', 'Summerlane Ave NE', '411035128016', $geo${"type":"Polygon","coordinates":[[[-85.58088126113954,43.0421258061761],[-85.58137312134791,43.04213311512664],[-85.58137680911071,43.04191359773071],[-85.58088637341618,43.04190632858202],[-85.58088126113954,43.0421258061761]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127014', '4271', 'Summerwind Ave NE', '411035127014', $geo${"type":"Polygon","coordinates":[[[-85.58213104289139,43.040250195199775],[-85.58263880844333,43.04024904282863],[-85.58264332040261,43.04002789744456],[-85.58212124980754,43.04003586984821],[-85.58213104289139,43.040250195199775]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127012', '4295', 'Summerwind Ave NE', '411035127012', $geo${"type":"Polygon","coordinates":[[[-85.58213787672128,43.04068671957368],[-85.58262981828165,43.040693033992916],[-85.58263428538064,43.04047150551343],[-85.58214050358826,43.04046855817259],[-85.58214103947218,43.0404805717609],[-85.58213787672128,43.04068671957368]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127015', '4259', 'Summerwind Ave NE', '411035127015', $geo${"type":"Polygon","coordinates":[[[-85.5821050338303,43.03981831924667],[-85.58210513081,43.03982704476969],[-85.58211850720375,43.03997635040496],[-85.58212124980754,43.04003586984821],[-85.58264332040261,43.04002789744456],[-85.58264782540624,43.039804502141386],[-85.5821050338303,43.03981831924667]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127019', '4226', 'Summerwind Ave NE', '411035127019', $geo${"type":"Polygon","coordinates":[[[-85.58112516971558,43.03921226973963],[-85.5817699428533,43.039554201581865],[-85.58177632500251,43.039545819018706],[-85.58179158310105,43.039530317264386],[-85.58180922505353,43.03951619053493],[-85.58182895671366,43.03950368762799],[-85.581850555281,43.03949292139159],[-85.5818736889208,43.03948408727077],[-85.58189805879373,43.03947727068563],[-85.58191196303224,43.03947470869735],[-85.58177419344992,43.03890859054765],[-85.58136087114987,43.03890422697507],[-85.58112516971558,43.03921226973963]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128011', '4317', 'Summerlane Ave NE', '411035128011', $geo${"type":"Polygon","coordinates":[[[-85.58090498777834,43.0410283557887],[-85.58139145088802,43.041035611991724],[-85.58139510151693,43.04081609493308],[-85.5809322916626,43.04080921970288],[-85.58092925406666,43.04081644156875],[-85.58092247749907,43.04083901550755],[-85.58091495339922,43.0408806421014],[-85.58091054770573,43.04091345350516],[-85.5809067044413,43.04094631461061],[-85.58090498777834,43.0410283557887]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127017', '4235', 'Summerwind Ave NE', '411035127017', $geo${"type":"Polygon","coordinates":[[[-85.58208921016421,43.039497172491785],[-85.58209691315763,43.03950076804112],[-85.58211716561252,43.039512847565305],[-85.58213535559497,43.03952656773106],[-85.5821512547285,43.03954173929697],[-85.58216463499554,43.03955817247479],[-85.58217534130313,43.03957562186592],[-85.58218318282987,43.03959386959769],[-85.58218654078415,43.03960673152079],[-85.58265300389915,43.03955450848144],[-85.58266611517921,43.03891800208525],[-85.58261891940452,43.03891750417405],[-85.58208921016421,43.039497172491785]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127029', '4342', 'Summerlane Ave NE', '411035127029', $geo${"type":"Polygon","coordinates":[[[-85.58015734663991,43.041465351489705],[-85.58015889815034,43.041465351374534],[-85.58065446144423,43.04146529737476],[-85.58065904979549,43.04124577047016],[-85.58016292783486,43.04124585810545],[-85.58016138040566,43.0412458584491],[-85.58015734663991,43.041465351489705]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127011', '4307', 'Summerwind Ave NE', '411035127011', $geo${"type":"Polygon","coordinates":[[[-85.58213449979162,43.04090859371968],[-85.582625282903,43.04091489329728],[-85.58262981828165,43.040693033992916],[-85.58213787672128,43.04068671957368],[-85.58213449979162,43.04090859371968]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127006', '4367', 'Summerwind Ave NE', '411035127006', $geo${"type":"Polygon","coordinates":[[[-85.58211034474229,43.04200599432114],[-85.58260304557338,43.04201232861452],[-85.58260747825808,43.04179285834441],[-85.58211350718314,43.04178650984939],[-85.58211034474229,43.04200599432114]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127025', '4294', 'Summerlane Ave NE', '411035127025', $geo${"type":"Polygon","coordinates":[[[-85.5801775284619,43.04045058176836],[-85.58017595700142,43.040452635256194],[-85.58017748241498,43.04045311646915],[-85.58075261037669,43.04063456085786],[-85.58077074432482,43.04060928723821],[-85.58079097276253,43.04057825683249],[-85.58081917236579,43.04054354641988],[-85.5808576521477,43.04049890339977],[-85.58089282712554,43.040465079923244],[-85.58038966677286,43.04017337327235],[-85.5801775284619,43.04045058176836]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127027', '4318', 'Summerlane Ave NE', '411035127027', $geo${"type":"Polygon","coordinates":[[[-85.58016541433346,43.041026337433664],[-85.58016695694671,43.04102633714087],[-85.58066360128507,43.04102627163466],[-85.58066534377471,43.04094362643122],[-85.58066416183422,43.04090063765357],[-85.58066994264092,43.040857849961014],[-85.58067645338848,43.0408217501925],[-85.58017175616118,43.0407660569974],[-85.580170200552,43.040765885312965],[-85.58016541433346,43.041026337433664]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127013', '4283', 'Summerwind Ave NE', '411035127013', $geo${"type":"Polygon","coordinates":[[[-85.58214050358826,43.04046855817259],[-85.58263428538064,43.04047150551343],[-85.58263880844333,43.04024904282863],[-85.58213104289139,43.040250195199775],[-85.58214050358826,43.04046855817259]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128012', '4329', 'Summerlane Ave NE', '411035128012', $geo${"type":"Polygon","coordinates":[[[-85.5809003997785,43.04124785530053],[-85.58138776231513,43.041255101750394],[-85.58139145088802,43.041035611991724],[-85.58090498777834,43.0410283557887],[-85.5809003997785,43.04124785530053]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128006', '4326', 'Summerwind Ave NE', '411035128006', $geo${"type":"Polygon","coordinates":[[[-85.58138776231513,43.041255101750394],[-85.58188100066208,43.04126244897716],[-85.58188528582076,43.04104295259643],[-85.58139145088802,43.041035611991724],[-85.58138776231513,43.041255101750394]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127024', '4282', 'Summerlane Ave NE', '411035127024', $geo${"type":"Polygon","coordinates":[[[-85.58066125641125,43.03981847938751],[-85.5804340565855,43.040115386275815],[-85.58092045777596,43.040443300674134],[-85.58093136273078,43.040434705799036],[-85.58097186706404,43.04040362508767],[-85.58101824070188,43.040374210740055],[-85.58106318960985,43.04034659557812],[-85.58111012168612,43.040320852676864],[-85.5811211644703,43.04031546705343],[-85.58066125641125,43.03981847938751]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127030', '4354', 'Summerlane Ave NE', '411035127030', $geo${"type":"Polygon","coordinates":[[[-85.58015331266004,43.041684872754736],[-85.58015486935118,43.04168487231343],[-85.58064987252142,43.041684796855165],[-85.58065446144423,43.04146529737476],[-85.58015889815034,43.041465351374534],[-85.58015734663991,43.041465351489705],[-85.58015331266004,43.041684872754736]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127023', '4270', 'Summerlane Ave NE', '411035127023', $geo${"type":"Polygon","coordinates":[[[-85.58066125641125,43.03981847938751],[-85.5811211644703,43.04031546705343],[-85.58115896232941,43.04029706535152],[-85.581209488753,43.04027529079506],[-85.58126158991992,43.04025558501826],[-85.58129875472667,43.04023924828821],[-85.58135746059955,43.040220570413155],[-85.58123335699611,43.03992908114284],[-85.58114090662917,43.0397118981749],[-85.58099860589047,43.039377655277676],[-85.58066125641125,43.03981847938751]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127005', '4379', 'Summerwind Ave NE', '411035127005', $geo${"type":"Polygon","coordinates":[[[-85.58210464661906,43.042404377142134],[-85.5825949852326,43.04240858915512],[-85.58260304557338,43.04201232861452],[-85.58211034474229,43.04200599432114],[-85.58210468863444,43.042401434728994],[-85.58210464661906,43.042404377142134]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127026', '4306', 'Summerlane Ave NE', '411035127026', $geo${"type":"Polygon","coordinates":[[[-85.580170200552,43.040765885312965],[-85.58017175616118,43.0407660569974],[-85.58067645338848,43.0408217501925],[-85.58067877923611,43.0408087458551],[-85.58069157291952,43.04075540099663],[-85.58070019674187,43.04073544219199],[-85.5807193625705,43.04068842396501],[-85.58074266871108,43.040648386882715],[-85.58075261037669,43.04063456085786],[-85.58017748241498,43.04045311646915],[-85.58017595700142,43.040452635256194],[-85.580170200552,43.040765885312965]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128002', '4374', 'Summerwind Ave NE', '411035128002', $geo${"type":"Polygon","coordinates":[[[-85.58137312134791,43.04213311512664],[-85.58186344731287,43.042140410524134],[-85.58186851819728,43.041920906412415],[-85.58137680911071,43.04191359773071],[-85.58137312134791,43.04213311512664]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035127010', '4319', 'Summerwind Ave NE', '411035127010', $geo${"type":"Polygon","coordinates":[[[-85.58213055188868,43.041128086554274],[-85.58262085051977,43.041134391299565],[-85.582625282903,43.04091489329728],[-85.58213449979162,43.04090859371968],[-85.58213330318144,43.04098656816819],[-85.58213055188868,43.041128086554274]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;

insert into public.lots
  (lot_number, street_number, street_name, parcel_pin, geometry_geojson)
values
  ('411035128009', '4288', 'Summerwind Ave NE', '411035128009', $geo${"type":"Polygon","coordinates":[[[-85.58139875265908,43.04059660527684],[-85.58188951528533,43.04060389635784],[-85.58189152361645,43.040356159209],[-85.58189027653815,43.04035616834095],[-85.58171964114561,43.04035740263188],[-85.5816729362722,43.04035852824199],[-85.58162454601539,43.04036148268051],[-85.58158008132963,43.04036617940436],[-85.5815252499622,43.04037452586834],[-85.58149073447736,43.04038101078128],[-85.58144794578594,43.04039104074804],[-85.58140956758781,43.04040278018763],[-85.581401947335,43.04040527587572],[-85.58139875265908,43.04059660527684]]]}$geo$::jsonb)
on conflict (parcel_pin) do update set
  street_number   = excluded.street_number,
  street_name     = excluded.street_name,
  geometry_geojson = excluded.geometry_geojson;
